version: '3'
services:
#  db:
#    image: mariadb:10.8.3
#    restart: always
#    ports:
#      - 33306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: qwer4321
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
#    volumes:
#      - mariadb-data-volume:/var/lib/mysql
#      - ./docker/db:/docker-entrypoint-initdb.d

  ror: &ror
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - bundle-volume:/usr/local/bundle
#    environment:
#      - WEBPACKER_DEV_SERVER_HOST=webpacker
#      - REDIS_URL_CACHING=redis://redis:6379/0

  app:
    <<: *ror
#    depends_on:
#      - db
#      - redis
#      - sidekiq
#      - webpacker

    ports:
      - 1234:1234

#  webpacker:
#    <<: *ror
#    environment:
#      - NODE_ENV=development
#      - RAILS_ENV=development
#      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
#    command: ./bin/webpack-dev-server
#    ports:
#      - 3035:3035

#  sidekiq:
#    <<: *ror
#    command: bundle exec sidekiq -C config/sidekiq.yml
#    depends_on:
#      - redis

  # Redis
#  redis:
#    image: redis
#    command: [ "redis-server", "--appendonly", "yes" ]
#    volumes:
#      - 'redis:/data'

#Volumes
volumes:
  bundle-volume:
#  mariadb-data-volume:
#  redis: